# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facial_recognition_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='facial_recognition_message.proto',
  package='ascend.presenter.facial_recognition',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n facial_recognition_message.proto\x12#ascend.presenter.facial_recognition\"\'\n\x0bRegisterApp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"^\n\x0e\x43ommonResponse\x12;\n\x03ret\x18\x01 \x01(\x0e\x32..ascend.presenter.facial_recognition.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x08\x43trlInfo\x12\x0e\n\x06\x62uzzer\x18\x01 \x01(\r\x12\x0c\n\x04open\x18\x02 \x01(\r\"%\n\x08\x46\x61\x63\x65Info\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"=\n\x03\x42ox\x12\x0c\n\x04lt_x\x18\x01 \x01(\r\x12\x0c\n\x04lt_y\x18\x02 \x01(\r\x12\x0c\n\x04rb_x\x18\x03 \x01(\r\x12\x0c\n\x04rb_y\x18\x04 \x01(\r\"i\n\x0b\x46\x61\x63\x65\x46\x65\x61ture\x12\x35\n\x03\x62ox\x18\x01 \x01(\x0b\x32(.ascend.presenter.facial_recognition.Box\x12\x13\n\x0b\x61live_score\x18\x02 \x01(\x02\x12\x0e\n\x06vector\x18\x03 \x03(\x02\"\xa2\x01\n\nFaceResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x45\n\x08response\x18\x02 \x01(\x0b\x32\x33.ascend.presenter.facial_recognition.CommonResponse\x12\x41\n\x07\x66\x65\x61ture\x18\x03 \x03(\x0b\x32\x30.ascend.presenter.facial_recognition.FaceFeature\"k\n\tFrameInfo\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x41\n\x07\x66\x65\x61ture\x18\x02 \x03(\x0b\x32\x30.ascend.presenter.facial_recognition.FaceFeature\x12\x0c\n\x04temp\x18\x03 \x01(\x02*\x7f\n\tErrorCode\x12\x0e\n\nkErrorNone\x10\x00\x12\x1a\n\x16kErrorAppRegisterExist\x10\x01\x12\x19\n\x15kErrorAppRegisterType\x10\x02\x12\x1a\n\x16kErrorAppRegisterLimit\x10\x03\x12\x0f\n\x0bkErrorOther\x10\x05\x62\x06proto3')
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='ascend.presenter.facial_recognition.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kErrorNone', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kErrorAppRegisterExist', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kErrorAppRegisterType', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kErrorAppRegisterLimit', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kErrorOther', index=4, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=735,
  serialized_end=862,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
kErrorNone = 0
kErrorAppRegisterExist = 1
kErrorAppRegisterType = 2
kErrorAppRegisterLimit = 3
kErrorOther = 5



_REGISTERAPP = _descriptor.Descriptor(
  name='RegisterApp',
  full_name='ascend.presenter.facial_recognition.RegisterApp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ascend.presenter.facial_recognition.RegisterApp.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ascend.presenter.facial_recognition.RegisterApp.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=112,
)


_COMMONRESPONSE = _descriptor.Descriptor(
  name='CommonResponse',
  full_name='ascend.presenter.facial_recognition.CommonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ascend.presenter.facial_recognition.CommonResponse.ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ascend.presenter.facial_recognition.CommonResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=208,
)


_CTRLINFO = _descriptor.Descriptor(
  name='CtrlInfo',
  full_name='ascend.presenter.facial_recognition.CtrlInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buzzer', full_name='ascend.presenter.facial_recognition.CtrlInfo.buzzer', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='ascend.presenter.facial_recognition.CtrlInfo.open', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=250,
)


_FACEINFO = _descriptor.Descriptor(
  name='FaceInfo',
  full_name='ascend.presenter.facial_recognition.FaceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ascend.presenter.facial_recognition.FaceInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='ascend.presenter.facial_recognition.FaceInfo.image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=289,
)


_BOX = _descriptor.Descriptor(
  name='Box',
  full_name='ascend.presenter.facial_recognition.Box',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lt_x', full_name='ascend.presenter.facial_recognition.Box.lt_x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lt_y', full_name='ascend.presenter.facial_recognition.Box.lt_y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rb_x', full_name='ascend.presenter.facial_recognition.Box.rb_x', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rb_y', full_name='ascend.presenter.facial_recognition.Box.rb_y', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=352,
)


_FACEFEATURE = _descriptor.Descriptor(
  name='FaceFeature',
  full_name='ascend.presenter.facial_recognition.FaceFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='ascend.presenter.facial_recognition.FaceFeature.box', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alive_score', full_name='ascend.presenter.facial_recognition.FaceFeature.alive_score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector', full_name='ascend.presenter.facial_recognition.FaceFeature.vector', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=459,
)


_FACERESULT = _descriptor.Descriptor(
  name='FaceResult',
  full_name='ascend.presenter.facial_recognition.FaceResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ascend.presenter.facial_recognition.FaceResult.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='ascend.presenter.facial_recognition.FaceResult.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature', full_name='ascend.presenter.facial_recognition.FaceResult.feature', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=624,
)


_FRAMEINFO = _descriptor.Descriptor(
  name='FrameInfo',
  full_name='ascend.presenter.facial_recognition.FrameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ascend.presenter.facial_recognition.FrameInfo.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature', full_name='ascend.presenter.facial_recognition.FrameInfo.feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='ascend.presenter.facial_recognition.FrameInfo.temp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=733,
)

_COMMONRESPONSE.fields_by_name['ret'].enum_type = _ERRORCODE
_FACEFEATURE.fields_by_name['box'].message_type = _BOX
_FACERESULT.fields_by_name['response'].message_type = _COMMONRESPONSE
_FACERESULT.fields_by_name['feature'].message_type = _FACEFEATURE
_FRAMEINFO.fields_by_name['feature'].message_type = _FACEFEATURE
DESCRIPTOR.message_types_by_name['RegisterApp'] = _REGISTERAPP
DESCRIPTOR.message_types_by_name['CommonResponse'] = _COMMONRESPONSE
DESCRIPTOR.message_types_by_name['CtrlInfo'] = _CTRLINFO
DESCRIPTOR.message_types_by_name['FaceInfo'] = _FACEINFO
DESCRIPTOR.message_types_by_name['Box'] = _BOX
DESCRIPTOR.message_types_by_name['FaceFeature'] = _FACEFEATURE
DESCRIPTOR.message_types_by_name['FaceResult'] = _FACERESULT
DESCRIPTOR.message_types_by_name['FrameInfo'] = _FRAMEINFO
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterApp = _reflection.GeneratedProtocolMessageType('RegisterApp', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERAPP,
  '__module__' : 'facial_recognition_message_pb2'
  # @@protoc_insertion_point(class_scope:ascend.presenter.facial_recognition.RegisterApp)
  })
_sym_db.RegisterMessage(RegisterApp)

CommonResponse = _reflection.GeneratedProtocolMessageType('CommonResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMONRESPONSE,
  '__module__' : 'facial_recognition_message_pb2'
  # @@protoc_insertion_point(class_scope:ascend.presenter.facial_recognition.CommonResponse)
  })
_sym_db.RegisterMessage(CommonResponse)

CtrlInfo = _reflection.GeneratedProtocolMessageType('CtrlInfo', (_message.Message,), {
  'DESCRIPTOR' : _CTRLINFO,
  '__module__' : 'facial_recognition_message_pb2'
  # @@protoc_insertion_point(class_scope:ascend.presenter.facial_recognition.CtrlInfo)
  })
_sym_db.RegisterMessage(CtrlInfo)

FaceInfo = _reflection.GeneratedProtocolMessageType('FaceInfo', (_message.Message,), {
  'DESCRIPTOR' : _FACEINFO,
  '__module__' : 'facial_recognition_message_pb2'
  # @@protoc_insertion_point(class_scope:ascend.presenter.facial_recognition.FaceInfo)
  })
_sym_db.RegisterMessage(FaceInfo)

Box = _reflection.GeneratedProtocolMessageType('Box', (_message.Message,), {
  'DESCRIPTOR' : _BOX,
  '__module__' : 'facial_recognition_message_pb2'
  # @@protoc_insertion_point(class_scope:ascend.presenter.facial_recognition.Box)
  })
_sym_db.RegisterMessage(Box)

FaceFeature = _reflection.GeneratedProtocolMessageType('FaceFeature', (_message.Message,), {
  'DESCRIPTOR' : _FACEFEATURE,
  '__module__' : 'facial_recognition_message_pb2'
  # @@protoc_insertion_point(class_scope:ascend.presenter.facial_recognition.FaceFeature)
  })
_sym_db.RegisterMessage(FaceFeature)

FaceResult = _reflection.GeneratedProtocolMessageType('FaceResult', (_message.Message,), {
  'DESCRIPTOR' : _FACERESULT,
  '__module__' : 'facial_recognition_message_pb2'
  # @@protoc_insertion_point(class_scope:ascend.presenter.facial_recognition.FaceResult)
  })
_sym_db.RegisterMessage(FaceResult)

FrameInfo = _reflection.GeneratedProtocolMessageType('FrameInfo', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEINFO,
  '__module__' : 'facial_recognition_message_pb2'
  # @@protoc_insertion_point(class_scope:ascend.presenter.facial_recognition.FrameInfo)
  })
_sym_db.RegisterMessage(FrameInfo)


# @@protoc_insertion_point(module_scope)
